import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThreadsBackground } from '@/shared/components/threads-background';
import { UsernameGuard } from '@/features/auth/components/username-guard';
import PageTransition from '@/shared/components/ui/page-transition';
import { SupportWidget } from '@/features/support/components/support-widget';

// import { SnowfallEffect } from '@/shared/components/snowfall-effect';

import { Toaster } from '@/shared/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThreadsBackground />

        <div style={{ position: 'relative', zIndex: 1 }}>
          <UsernameGuard />

          <PageTransition>{children}</PageTransition>
          <Toaster position="top-center" richColors />
          <SupportWidget />
        </div>
      </body>
    </html>
  );
}
